//
//  OrderMainModel.swift
//  KingPowerModel
//
//  Created by Warunee Phattharakijwanich on 10/3/2558 BE.
//  Copyright © 2558 IBM. All rights reserved.
//

import Foundation

public class OrderMainModel{
    
    var ordm_id         : Int32 = 0
    var ordm_ords_id    : Int32 = 0
    var ordm_user_id    : Int32 = 0
    var ordm_cust_id    : Int32 = 0
    var ordm_no : String = ""
    var ordm_currency   : String = ""
    var ordm_flight_departure : Int32 = 0
    var ordm_receipt_departure : String = ""
    var ordm_picknow_flag : String = ""
    var ordm_flight_arrival : Int32 = 0
    var ordm_receipt_arrival : String = ""
    var ordm_picklater_flag : String = ""
    var ordm_passport_no : String = ""
    var ordm_current_location : String = ""
    var ordm_pickup_location : String = ""
    var ordm_total_price : Double = 0
    var ordm_submit_date : String = ""
    var ordm_create_date : String = ""
    var ordm_update_date : String = ""
    //    var ordm_submit_date : NSDate = NSDate()
    //    var ordm_create_date : NSDate = NSDate()
    //    var ordm_update_date : NSDate = NSDate()
    var ordm_running_no  : Int32 = 0
    var ordm_net_total_price : Double = 0
    var ordm_card_discount : Int32 = 0
    
    var ordm_ords        : [OrderDetailModel]!
    var queryInsertOrderMain : String = "INSERT INTO ORDER_MAIN (ORDM_ORDS_ID, ORDM_USER_ID, ORDM_CUST_ID, ORDM_NO, ORDM_PASSPORT_NO, ORDM_CURRENCY, ORDM_TOTAL_PRICE, ORDM_FLIGHT_DEPARTURE, ORDM_RECEIPT_DEPARTURE, ORDM_PICKNOW_FLAG, ORDM_CURRENT_LOCATION, ORDM_FLIGHT_ARRIVAL, ORDM_RECEIPT_ARRIVAL, ORDM_PICKLATER_FLAG, ORDM_PICKUP_LOCATION, ORDM_SUBMIT_DATE, ORDM_CREATE_DATE, ORDM_UPDATE_DATE, ORDM_RUNNING_NO, ORDM_NET_TOTAL_PRICE, ORDM_CARD_DISCOUNT) VALUES (%d, %d, %d, '%@', '%@', '%@', %f, %d, '%@', '%@', '%@', %d, '%@', '%@', '%@', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, %d, %f, %d);"
    
    var queryUpdateOrderStatusById : String = "UPDATE ORDER_MAIN SET ORDM_ORDS_ID = %d, ORDM_UPDATE_DATE = %@ WHERE ORDM_ID = %d"
    
    var queryUpdateReceiptDepartureById : String = "UPDATE ORDER_MAIN SET ORDM_RECEIPT_DEPARTURE = '%@', ORDM_UPDATE_DATE = %@ WHERE ORDM_ID = %d"
    
    var queryUpdateReceiptArrivalById : String = "UPDATE ORDER_MAIN SET ORDM_RECEIPT_ARRIVAL = '%@', ORDM_UPDATE_DATE = %@ WHERE ORDM_ID = %d"
    
    var queryGetOrderMainById : String = "SELECT ORDM_ID, ORDM_ORDS_ID, ORDM_USER_ID, ORDM_CUST_ID, ORDM_NO, ORDM_PASSPORT_NO, ORDM_CURRENCY, ORDM_TOTAL_PRICE, ORDM_FLIGHT_DEPARTURE, ORDM_RECEIPT_DEPARTURE, ORDM_PICKNOW_FLAG, ORDM_CURRENT_LOCATION, ORDM_FLIGHT_ARRIVAL, ORDM_RECEIPT_ARRIVAL, ORDM_PICKLATER_FLAG, ORDM_PICKUP_LOCATION, ORDM_SUBMIT_DATE, ORDM_CREATE_DATE, ORDM_UPDATE_DATE, ORDM_RUNNING_NO, ORDM_NET_TOTAL_PRICE, ORDM_CARD_DISCOUNT FROM ORDER_MAIN WHERE ORDM_ID = %d ORDER BY %@, %@;"
    
    var queryGetOrderMainByCustomerId : String = "SELECT ORDM_ID, ORDM_ORDS_ID, ORDM_USER_ID, ORDM_CUST_ID, ORDM_NO, ORDM_PASSPORT_NO, ORDM_CURRENCY, ORDM_TOTAL_PRICE, ORDM_FLIGHT_DEPARTURE, ORDM_RECEIPT_DEPARTURE, ORDM_PICKNOW_FLAG, ORDM_CURRENT_LOCATION, ORDM_FLIGHT_ARRIVAL, ORDM_RECEIPT_ARRIVAL, ORDM_PICKLATER_FLAG, ORDM_PICKUP_LOCATION, ORDM_SUBMIT_DATE, ORDM_CREATE_DATE, ORDM_UPDATE_DATE, ORDM_RUNNING_NO, ORDM_NET_TOTAL_PRICE, ORDM_CARD_DISCOUNT FROM ORDER_MAIN WHERE ORDM_CUST_ID = %d ORDER BY %@;"
    
    var queryGetMaxTodayRunningNo : String = "SELECT MAX(ORDM_RUNNING_NO) AS MAX_COL FROM ORDER_MAIN WHERE DATE(ORDM_CREATE_DATE) = CURRENT_DATE"
    
    var queryGetOrderMainByMaxRunningNo : String = "SELECT ORDM_ID, ORDM_ORDS_ID, ORDM_USER_ID, ORDM_CUST_ID, ORDM_NO, ORDM_PASSPORT_NO, ORDM_CURRENCY, ORDM_TOTAL_PRICE, ORDM_FLIGHT_DEPARTURE, ORDM_RECEIPT_DEPARTURE, ORDM_PICKNOW_FLAG, ORDM_CURRENT_LOCATION, ORDM_FLIGHT_ARRIVAL, ORDM_RECEIPT_ARRIVAL, ORDM_PICKLATER_FLAG, ORDM_PICKUP_LOCATION, ORDM_SUBMIT_DATE, ORDM_CREATE_DATE, ORDM_UPDATE_DATE, ORDM_RUNNING_NO, ORDM_NET_TOTAL_PRICE, ORDM_CARD_DISCOUNT FROM ORDER_MAIN WHERE ORDM_NO = '%@';"
    
    var queryGetOrderMainByCurrentDate : String = "SELECT ORDM_ID, ORDM_ORDS_ID, ORDM_USER_ID, ORDM_CUST_ID, ORDM_NO, ORDM_PASSPORT_NO, ORDM_CURRENCY, ORDM_TOTAL_PRICE, ORDM_FLIGHT_DEPARTURE, ORDM_RECEIPT_DEPARTURE, ORDM_PICKNOW_FLAG, ORDM_CURRENT_LOCATION, ORDM_FLIGHT_ARRIVAL, ORDM_RECEIPT_ARRIVAL, ORDM_PICKLATER_FLAG, ORDM_PICKUP_LOCATION, strftime('%%d/%%m/%%Y %%H:%%M:%%S', ORDM_SUBMIT_DATE) ORDM_SUBMIT_DATE, strftime('%%d/%%m/%%Y %%H:%%M:%%S', ORDM_CREATE_DATE) ORDM_CREATE_DATE, strftime('%%d/%%m/%%Y %%H:%%M:%%S', ORDM_UPDATE_DATE) ORDM_UPDATE_DATE, ORDM_RUNNING_NO, ORDM_NET_TOTAL_PRICE, ORDM_CARD_DISCOUNT FROM ORDER_MAIN WHERE DATE(SUBSTR(ORDM_SUBMIT_DATE, 1,10)) = DATE('NOW') AND ORDM_CUST_ID = %d ORDER BY ORDM_SUBMIT_DATE DESC"
    
    var queryGetOrderMainByHistoryDate : String = "SELECT ORDM_ID, ORDM_ORDS_ID, ORDM_USER_ID, ORDM_CUST_ID, ORDM_NO, ORDM_PASSPORT_NO, ORDM_CURRENCY, ORDM_TOTAL_PRICE, ORDM_FLIGHT_DEPARTURE, ORDM_RECEIPT_DEPARTURE, ORDM_PICKNOW_FLAG, ORDM_CURRENT_LOCATION, ORDM_FLIGHT_ARRIVAL, ORDM_RECEIPT_ARRIVAL, ORDM_PICKLATER_FLAG, ORDM_PICKUP_LOCATION, strftime('%%d/%%m/%%Y %%H:%%M:%%S', ORDM_SUBMIT_DATE) ORDM_SUBMIT_DATE, strftime('%%d/%%m/%%Y %%H:%%M:%%S', ORDM_CREATE_DATE) ORDM_CREATE_DATE, strftime('%%d/%%m/%%Y %%H:%%M:%%S', ORDM_UPDATE_DATE) ORDM_UPDATE_DATE, ORDM_RUNNING_NO, ORDM_NET_TOTAL_PRICE, ORDM_CARD_DISCOUNT FROM ORDER_MAIN WHERE DATE(SUBSTR(ORDM_SUBMIT_DATE, 1,10)) < DATE('NOW') AND ORDM_CUST_ID = %d ORDER BY ORDM_SUBMIT_DATE DESC"
}